api = "0.2"

[buildpack]
  id = "paketo-community/staticfile"
  name = "Staticfile Buildpack"
  version = "0.0.2"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/build","bin/detect","buildpack.toml","server_configs/nginx.conf"]
  pre_package = "./scripts/build.sh"
