resources:
- name: staticfile-buildpack
  type: git
  icon: github
  source:
    uri: https://github.com/EngineerBetter/staticfile.git
    tag_filter: v*.*.*

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: staticfile-buildpack
    trigger: true
  - set_pipeline: self
    file: staticfile-buildpack/ci/pipeline.yml

- name: build-staticfile-buildpack
  plan:
  - get: staticfile-buildpack
    trigger: true
    passed:
    - set-pipeline
  - load_var: tag
    file: staticfile-buildpack/.git/ref
  - task: package-buildpack
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: engineerbetter/pcf-ops
      inputs:
      - name: staticfile-buildpack
      outputs:
      - name: staticfile-buildpack
      run:
        dir: staticfile-buildpack
        path: scripts/package.sh
        args: [--version, ((.:tag))]
  - task: push-staticfile-buildpack-image
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ananace/skopeo
      inputs:
      - name: staticfile-buildpack
      run:
        path: skopeo
        args:
        - copy
        - oci-archive:staticfile-buildpack/build/buildpackage.cnb
        - docker://engineerbetter/staticfile-buildpack:((.:tag))
        - --dest-creds
        - ((dockerhub_user)):((dockerhub_password))
